const repository = require('./storeRepository');

module.exports = {
    addUserXp: repository.addUserXp,
    adjustUserXp: repository.adjustUserXp,
    countProcessedLevelMessage: repository.countProcessedLevelMessage,
    createLevelImportJob: repository.createLevelImportJob,
    createLevelTestSession: repository.createLevelTestSession,
    getLevelImportJob: repository.getLevelImportJob,
    getLevelRank: repository.getLevelRank,
    getLevelTestSession: repository.getLevelTestSession,
    getUserLevelRecord: repository.getUserLevelRecord,
    insertLevelImportMessage: repository.insertLevelImportMessage,
    insertLevelReconciliationRecord: repository.insertLevelReconciliationRecord,
    insertLevelXpEvent: repository.insertLevelXpEvent,
    listLevelImportCheckpoints: repository.listLevelImportCheckpoints,
    listLevelImportJobs: repository.listLevelImportJobs,
    listLevelImportMessages: repository.listLevelImportMessages,
    listLevelLeaderboard: repository.listLevelLeaderboard,
    listLevelProcessedMessages: repository.listLevelProcessedMessages,
    listLevelReconciliationRecords: repository.listLevelReconciliationRecords,
    listLevelRoleMappings: repository.listLevelRoleMappings,
    listLevelTestSessions: repository.listLevelTestSessions,
    listLevelXpEvents: repository.listLevelXpEvents,
    markLevelImportMessageProcessed: repository.markLevelImportMessageProcessed,
    removeLevelRoleMapping: repository.removeLevelRoleMapping,
    requestCancelLevelImportJob: repository.requestCancelLevelImportJob,
    setUserXp: repository.setUserXp,
    setUserXpMinimum: repository.setUserXpMinimum,
    updateLevelImportJob: repository.updateLevelImportJob,
    updateLevelTestSession: repository.updateLevelTestSession,
    upsertLevelImportCheckpoint: repository.upsertLevelImportCheckpoint,
    upsertLevelRoleMapping: repository.upsertLevelRoleMapping,
};
