const repository = require('./storeRepository');

module.exports = {
    addUserXp: repository.addUserXp,
    adjustUserXp: repository.adjustUserXp,
    applyLevelProbotFinalMigration: repository.applyLevelProbotFinalMigration,
    countProcessedLevelMessage: repository.countProcessedLevelMessage,
    createLevelCalibrationJob: repository.createLevelCalibrationJob,
    createLevelImportJob: repository.createLevelImportJob,
    createLevelTestSession: repository.createLevelTestSession,
    getLevelCalibrationJob: repository.getLevelCalibrationJob,
    getLevelImportJob: repository.getLevelImportJob,
    getLevelProbotMigrationBatch: repository.getLevelProbotMigrationBatch,
    getLevelRank: repository.getLevelRank,
    getLevelTestSession: repository.getLevelTestSession,
    getUserLevelRecord: repository.getUserLevelRecord,
    insertLevelImportMessage: repository.insertLevelImportMessage,
    insertLevelReconciliationRecord: repository.insertLevelReconciliationRecord,
    insertLevelXpEvent: repository.insertLevelXpEvent,
    listLevelImportCheckpoints: repository.listLevelImportCheckpoints,
    listLevelImportJobs: repository.listLevelImportJobs,
    listLevelImportMessages: repository.listLevelImportMessages,
    listLevelImportMessagesPage: repository.listLevelImportMessagesPage,
    listLevelCalibrationJobs: repository.listLevelCalibrationJobs,
    listLevelLeaderboard: repository.listLevelLeaderboard,
    listLevelProbotMigrationBatches: repository.listLevelProbotMigrationBatches,
    listLevelProbotMigrationSnapshots: repository.listLevelProbotMigrationSnapshots,
    listLevelProcessedMessages: repository.listLevelProcessedMessages,
    listLevelReconciliationRecords: repository.listLevelReconciliationRecords,
    listLevelRoleMappings: repository.listLevelRoleMappings,
    listLevelTestSessions: repository.listLevelTestSessions,
    listLevelXpEvents: repository.listLevelXpEvents,
    markLevelImportMessageProcessed: repository.markLevelImportMessageProcessed,
    removeLevelRoleMapping: repository.removeLevelRoleMapping,
    requestCancelLevelCalibrationJob: repository.requestCancelLevelCalibrationJob,
    requestCancelLevelImportJob: repository.requestCancelLevelImportJob,
    rollbackLevelProbotFinalMigration: repository.rollbackLevelProbotFinalMigration,
    setUserXp: repository.setUserXp,
    setUserXpMinimum: repository.setUserXpMinimum,
    updateLevelImportJob: repository.updateLevelImportJob,
    updateLevelCalibrationJob: repository.updateLevelCalibrationJob,
    updateLevelTestSession: repository.updateLevelTestSession,
    upsertLevelImportCheckpoint: repository.upsertLevelImportCheckpoint,
    upsertLevelRoleMapping: repository.upsertLevelRoleMapping,
};
